spring:
  application:
    name: escape_room_be
  datasource:
    url: jdbc:mysql://localhost:3306/escape_room_demo?CharacterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace